---
title: "Lanzamiento de la Diplomatura en Generación y Análisis de Información en Turismo"
description: |
  Iniciativa del Ministerio de Turismo y Deportes de la Nación y la Universidad Nacional de San Martín (UNSAM)
preview: https://bitacora.yvera.tur.ar/posts/bienvenida/sinta.png
date: 2023-06-12
output:
  distill::distill_article:
    self_contained: true
---

Aunque no es condición necesaria, el programa está pensado especialmente para referentes productores de estadística de turismo de provincias y municipios, con el objetivo de f**ortalecer el análisis de la información del sector turístico y adquirir nuevas herramientas**, introduciendo el lenguaje de programación **`R`** para poder llevar adelante cada tarea y etapa del procesamiento, análisis y reporte de datos turísticos.

**Es gratuita - el arancel está 100% bonificado por el Ministerio de Turismo y Deportes - y consta de 60 horas de formación**, distribuidas desde agosto hasta noviembre, los días lunes y jueves de 18.30 a 20.30 horas. Los requisitos para la obtención del certificado serán presentar un trabajo final integrador y se requerirá un 75% de asistencia.

La **modalidad de cursada será virtual**, con el fin de poder hacer accesible esta propuesta de capacitación en todos los rincones de la geografía nacional, combinando clases asincrónicas y clases en tiempo real.

## Cronograma 

**Inicio de Inscripción:** 12 de junio de 2023. Cierre de inscripciones: 4 de julio de 2023.\
\
**Confirmación de postulantes:** del 13 al 20 de julio de 2023.\
\
**Inicio de cursada:** 3 de agosto de 2023.

**Ante dudas o consultas, [podés acceder al archivo de preguntas frecuentes](https://www.argentina.gob.ar/sites/default/files/preguntas_frecuentes_-_diplomatura_0.pdf) o dirigirte por correo electrónico a [estadistica\@turismo.gob.ar](mailto:estadistica@turismo.gob.ar){.email}**

## ARMONIZACIN 

El programa se enmarca en el desarrollo de acciones propuestas en el proyecto de [Armonización de Estadísticas Provinciales de Turismo](https://armonizacion.yvera.tur.ar/)
que la Dirección Nacional de Mercados y Estadística reeditó a partir del año 2021. El mismo se propuso contribuir al fortalecimiento de los sistemas de estadística provinciales con el objetivo de generar información robusta y confiable de la actividad turística, a partir de tres ejes principales:

(i) **actualización metodológica**, que promovimos con el desarrollo de Documentos Técnicos, publicados bajo la etiqueta Metodología en la [BIBLIOTECA del Sistema de Información Turístico de la Argentina (SINTA)](https://biblioteca.yvera.tur.ar/)
    [^1];

(ii) **coordinación y gestión de datos**, para lo que se avanzó en el desarrollo del [*Sistema Federal de Gestión de Datos de Turismo* (`<data>TUR`)](https://datatur.yvera.tur.ar/);

(iii) **capacitaciones** (experiencia grabada y editada para luego ser compartida junto al resto del material para todo público de manera asincrónica).

[^1]: Los documentos son: Documento Técnico \#1: Conceptos y elementos básicos para la medición provincial de los turistas; Documento Técnico \#2: Propuestas metodológicas para las encuestas de ocupación en alojamientos turísticos; Documento Técnico \#3: Descripción, análisis y utilización de los Registros Administrativos para la medición del Turismo; Documento Técnico \#4: Propuestas Metodológicas para las Encuestas de Perfil del Visitante; Documento Técnico \#5: Medición de la contribución económica del turismo: actividad y empleo; Documento Técnico \#6: Ciencia de Datos para el Turismo: Se encuentran disponible en la BIBLIOTECA <https://bitacora.yvera.tur.ar/>

El trabajo coordinado entre la Dirección Nacional de Calidad e Innovación Turística (Subsecretaría de Calidad, Accesibilidad y Sustentabilidad); la Dirección Nacional de Mercados y Estadística (Subsecretaría de Desarrollo Estratégico) y la UNSAM posibilitó el diseño y elaboración de un programa que busca fortalecer las capacidades de las y los referentes técnicos para poder mejorar la producción de estadísticas locales derivadas de los operativos de encuesta, explotación de registros administrativos y otras fuentes de información utilizadas.

Esta propuesta educativa forma parte del Plan Estratégico de Calidad y Formación que lleva a cabo la cartera nacional de Turismo y Deportes a través de la Subsecretaría de Calidad, Accesibilidad y Sustentabilidad del Turismo Nacional, articulando con otros organismos, y que tiene como objetivos mejorar la competitividad en el sector, fortalecer los destinos turísticos e incorporar nuevas herramientas de trabajo.

** [INSCRIPCIONES AQU](https://www.argentina.gob.ar/turismoydeportes/capacitate-turismo/diplomatura-en-generacion-y-analisis-de-informacion-en-turismo-0)**
